CMakeLists.txt

simplify consumption of SDKs (for windows tunneler)

add install headers and libraries

---

include/ziti/ziti_tunneler.h
lib/intercept.c
lib/intercept.h
lib/ziti_tunneler.c
lib/ziti_tunneler_cbs.c
programs/ziti-tunneler/ziti-tunneler.c

service IDs are unique across all ziti contexts, so use the ID to identify intercepts that are being removed.

remove intercepts by service ID instead of name

---

include/ziti/ziti_tunneler.h
lib/tunneler_tcp.c
lib/tunneler_udp.c
lib/ziti_tunneler_cbs.c
lib/ziti_tunneler_priv.h

Don't dereference the tunneler io context.
As this PR (draft) stands now it is working well for tcp intercept. I'll update udp with another commit but wanted to make this much available if it's useful.

Io context stability

---

lib/intercept.c
lib/lwip/lwipopts.h
lib/tunneler_tcp.c
lib/tunneler_udp.c
lib/ziti_tunneler.c
lib/ziti_tunneler_cbs.c
lib/ziti_tunneler_priv.h
programs/ziti-tunneler/netif_driver/darwin/utun.c

This PR mainly fixes an issue that caused the tunneler SDK to incorrectly intercept retried SYN segments instead of letting lwip handle them (commit 1c252ad). With this change the Darwin and linux tunnelers have been running iperf loops for hours.
Along the way I also added some logging improvements that are worthwhile. 
Finally, this PR includes a change to the Darwin tun polling that reduces latency by letting uv poll the tun directly (via uv_poll) instead of calling `poll()` from a uv_check callback (commit 1214626).

Lwip stability

---

lib/tunnel_tcp.c
lib/ziti_tunnel.c
programs/ziti-edge-tunnel/dnsmasq_manager.c

bandaid to prevent double close

Avoid circular lwip pcb list

---

include/ziti/ziti_tunnel.h
include/ziti/ziti_tunnel_cbs.h
lib/tunnel_tcp.c
lib/tunnel_tcp.h
lib/tunnel_udp.c
lib/tunnel_udp.h
lib/ziti_tunnel.c
lib/ziti_tunnel_cbs.c
lib/ziti_tunnel_priv.h
programs/ziti-edge-tunnel/ziti-edge-tunnel.c

Look for active connections when `ziti_tunneler_stop_intercepting` is called.
This change also moves the tnlr_io context that gets passed to callbacks into a common structure, so the ziti callbacks and the tsk callbacks are handing the same pointer. I expect this to solve the invalid tnlr_io issues that Dariusz was seeing when running through Valtix.

Kill active connections

---

README.md
include/ziti/ziti_tunnel.h
include/ziti/ziti_tunnel_cbs.h
lib/tunnel_tcp.c
lib/ziti_tunnel.c
lib/ziti_tunnel_cbs.c
programs/ziti-edge-tunnel/ziti-edge-tunnel.c

should resolve the issue the Ziti Desktop Edge for Windows sees when accessing a fileshare

cleanup handling of pointer when client issues rst

---

lib/tunnel_tcp.c
lib/tunnel_udp.c
lib/ziti_tunnel.c
lib/ziti_tunnel_cbs.c

ziti_write calls the write callback in all cases (even on early error), so free the write context in the callback and nowhere else.

only free write_ctx in on_ziti_write

---

lib/tunnel_tcp.c
lib/tunnel_udp.c

the write callback frees the pbuf and ziti_sdk_c_write calls the callback when ziti_write fails

don't double free pbuf when ziti_sdk_c_write fails.

---

CMakeLists.txt
lib/ziti_tunnel_cbs.c

despite taking a bool that indicates whether or not the dial succeeded, ziti_tunnel_dial_completed should only be called when the dial was successful.

Don't ack client when dial failed

---

lib/ziti_tunnel.c
lib/ziti_tunnel_cbs.c

prevent crashes when messages arrive on connections for services that are no longer intercepted. don't rely on the edge router to close the ziti side.

explicitly close ziti when killing connections of removed intercepts

---

CMakeLists.txt
lib/ziti_tunnel.c
programs/ziti-edge-tunnel/ziti-edge-tunnel.c

The underlay connection gets closed in the ziti_close callback.

always close ziti connection first

---

lib/tunnel_udp.c

pbuf_cat takes over our reference to the tail (incoming) packet buffer, which leads to an assert when the pbuf is later free'd in tunneler_udp_ack:
Assertion "pbuf_free: p->ref > 0" failed at line 753 in _deps/lwip-src/src/core/pbuf.c
This issue is only be observed if a UDP client sends more than one datagram (including the initially intercepted datagram) before ziti_dial completes.
Use pbuf_chain to link incoming packet buffers, so we can free each pbuf individually as the associated `ziti_write`s complete.

use pbuf_chain when enqueuing UDP payloads

---

lib/ziti_hosting.c

update hosting code accordingly after #114 - use app_data_sz instead of expecting the json to be NUL-terminated

use app_data_sz instead of requiring NUL-terminated json string for tunneler_app_data

---

CMakeLists.txt
programs/ziti-edge-tunnel/ziti-edge-tunnel.c

new `ziti-edge-tunnel` options
`-i|--identity` can be repeated multiple times to load multiple identities
`-I|--identity-dir` can be used to load all identities from a directory

multiple identity support

---

lib/ziti_hosting.c
lib/ziti_tunnel_cbs.c

One crash happens on intercepting tunneler when source_ip is set in intercept.v1 config
The other happens on hosting tunneler when `on_hosted_client_connect` fails for any reason.

Fix crashes

---

lib/ziti_hosting.c

valgrind flagged an uninitialized read. and fix a log formatting typo.

initialize address info hints when looking up source ip. fix logging.

---

lib/ziti_hosting.c

This fixes the crash that I was seeing when uv_tcp_bind failed to set sourceIp. The close needs to be initiated with hosted_server_close so that the io_ctx (which holds the uv handle) isn't free'd prematurely.

initiate session close with hosted_server_close

---

CMakeLists.txt
include/ziti/ziti_tunnel.h
lib/ziti_hosting.c
lib/ziti_tunnel.c
lib/ziti_tunnel_cbs.c
programs/ziti-edge-tunnel/ziti-edge-tunnel.c

* add `client_protocol`, `client_ip`, and `client_port` to the map in tunneler_app_data when dialing
* resolve $client_ip, $client_port references in `sourceIp` value.

Support client address variables in intercept.v1:sourceIp

---

CMakeLists.txt
lib/ziti_tunnel.c

Don't retain the pbuf for dns queries for the entire duration of the query.

free pbuf for dns query before query goes onto work queue

---

lib/ziti-tunnel-cbs/ziti_hosting.c
lib/ziti-tunnel-cbs/ziti_tunnel_cbs.c

hosting side would error out of peer sent empty `source_ip`

better handle empty source_ip string

---

lib/ziti-tunnel/tunnel_udp.c

fixes a crash that a few people have seen already.

pass app context to ziti_sdk_c_dial when intercepting udp.

---

CMakeLists.txt

fixes memory leak at the transport layer library

ziti-sdk-c update 0.24.3

---

lib/ziti-tunnel-cbs/ziti_hosting.c

Ziti Connection was not torn down if there were outstanding ziti write requests at tcp.eof

Fix hosted connection close

---

lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c
lib/ziti-tunnel/ziti_tunnel.c
programs/ziti-edge-tunnel/instance.c
programs/ziti-edge-tunnel/ziti-edge-tunnel.c

ziti-edge-tunnel was crashing due to freeing invalid pointer. This PR addresses the crash and cleans up some of the warnings.
A number of leaks are also identified (with todos) but not addressed here.

Fix crash and some warnings

---

lib/ziti-tunnel-cbs/include/ziti/ziti_dns.h
lib/ziti-tunnel-cbs/ziti_dns.c
programs/ziti-edge-tunnel/netif_driver/linux/tun.c
programs/ziti-edge-tunnel/ziti-edge-tunnel.c

The following methods are discovered and supported:
* resolvectl
* systemd-resolve
* resolvconf
* /etc/resolv.conf modification as the last resort

more robust linux DNS integration

---

deps/CMakeLists.txt

git.savannah.nongnu.org has been really flaky recently

use lwip github repos

---

CMakeLists.txt
lib/ziti-tunnel-cbs/ziti_hosting.c

if we get an error resolving/binding underlay incoming client connection is not closed and is leaked

Fix conn leak

---

CMakeLists.txt

James ran into the illegal instruction crash when testing 0.17.21. There's a bunch of stuff on `main` since 0.17.21 that I don't think is ready for customers yet so I'm creating a 0.17.x branch.

update ziti sdk to 0.26.18 for libsodium build fixes (v0.17.x)

---

lib/ziti-tunnel-cbs/CMakeLists.txt
lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c
lib/ziti-tunnel/include/ziti/ziti_tunnel.h
lib/ziti-tunnel/ziti_tunnel_priv.h
programs/ziti-edge-tunnel/CMakeLists.txt

TNL_LOG was crashing on Windows, fyi.

update logger function to match updated ziti_log signature

---

CMakeLists.txt
programs/ziti-edge-tunnel/include/instance.h
programs/ziti-edge-tunnel/include/model/dtos.h
programs/ziti-edge-tunnel/include/model/events.h
programs/ziti-edge-tunnel/include/windows/windows-scripts.h
programs/ziti-edge-tunnel/instance.c
programs/ziti-edge-tunnel/netif_driver/windows/tun.c
programs/ziti-edge-tunnel/netif_driver/windows/tun.h
programs/ziti-edge-tunnel/windows-scripts.c
programs/ziti-edge-tunnel/ziti-edge-tunnel.c

This PR contains the below functionalities.
1. During windows upgrade, the identity files will be backed up to a backup folder. The backup files will be in the windows.old or windows.~bt path. So WDE will search for the identities files in those paths and if it find any identities, those files will be moved to the config/identity path.
2. fixes for the set and get log level. Changed it from char* to int value.
3. Update the interface metric to 255 when nrpt is effective/dns flag is off. Update the interface metric to 5 when nrpt is not effective/dns flag is on.

Copy file from windows bkp folder, log level fix and interface metric update

---

lib/ziti-tunnel/lwip/lwipopts.h
lib/ziti-tunnel/tunnel_tcp.c

prevent connection leaks from misbehaving clients

enable TCP KEEPALIVE on tunneler TCP connections

---

lib/ziti-tunnel/include/ziti/ziti_tunnel.h
lib/ziti-tunnel/ziti_tunnel.c
lib/ziti-tunnel/ziti_tunnel_priv.h
programs/ziti-edge-tunnel/include/windows/windows-scripts.h
programs/ziti-edge-tunnel/include/windows/windows-service.h
programs/ziti-edge-tunnel/netif_driver/windows/tun.c
programs/ziti-edge-tunnel/windows-scripts.c
programs/ziti-edge-tunnel/windows-service.c
programs/ziti-edge-tunnel/ziti-edge-tunnel.c

Provide a helper function that any thread can use to run a function from the loop's thread.
Currently the tunneler context is not available to the windows SCM module. I envision changing the way the SCM code integrates into the tSDK, so that the tunneler context is visible and can be used when calling `ziti_tunnel_async_send`. In the meantime I added static semaphore
to protect the default loop when the tunneler context is passed as NULL.
I have not looked at using this to run the nrpt scripts. I wanted to understand more about the scripts before assuming `ziti_tunnel_async_send` is appropriate for them.

Avoid.concurrency.with.loop

---

lib/ziti-tunnel-cbs/dns_host.h
programs/ziti-edge-tunnel/instance-config.c
programs/ziti-edge-tunnel/windows-service.c
programs/ziti-edge-tunnel/ziti-edge-tunnel.c

get back on the uv loop and clean up. use `uv_cond_wait` to wait until that process completes then exit the main thread after notifying the SCM.

Stop service without uv stop

---

.github/workflows/cmake.yml
.github/workflows/mattermost-ziti-webhook.yml
.gitignore
programs/ziti-edge-tunnel/CMakeLists.txt
programs/ziti-edge-tunnel/netif_driver/linux/resolvers.c
programs/ziti-edge-tunnel/netif_driver/linux/resolvers.h
programs/ziti-edge-tunnel/netif_driver/linux/tun.c
programs/ziti-edge-tunnel/netif_driver/linux/utils.c
programs/ziti-edge-tunnel/netif_driver/linux/utils.h

This PR adds `systemd-resolved` integration via `libsystemd`'s `sd-bus` API. 
A cmake feature flag is included for conditional compilation. Additionally, libsystemd is loaded dynamically at runtime, with fallback to the existing implementation in the case of load failure. 
This approach has some distinct advantages:
* Removes the need to install and run systemd inside container environment. 
- Only the DBus socket must be shared between the host and container. 
* Detects whether systemd-resolved is registered with DBus, doesn't guess based on list of available binaries
- Handles systemd installed, but not booted
* Opens the door to respond to signals emitted from DBus in the future. 
- Example: a route only domain is added to a separate interface, and we want to ensure our interface also …

Replaces shell commands with direct systemd-resolved integration

---

CMakeLists.txt

This PR fixes two problems that were introduced with #321:
* bundled zip archives were corrupt; we change the bundle command from `tar --format=7zip` back to `7z`
* `GIT_VERSION` needed to be available. this doesn't work when using a remote host toolchain in clion

fix build issues

---

lib/ziti-tunnel/ziti_tunnel.c

(allows uv_loop to exit following ziti_shutdown)

un_ref the check_lwip_timeouts timer 

---

docker/docker-compose.yml

enhance docker entrypoint
preserve Docker Compose examples for dnsmasq as a reference
reconcile entrypoint variants for multi-id and stdin

resume sourcing latest container image tag

---

lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c

the ziti dump data is getting appended to the file, if file already exists. I have changed the file mode to w+, so if file exists, it will overwrite the file.

overwrite ziti dump file, if old file exists

---

.github/workflows/cpack.yml

Container-based builds fail with the following error whenever the directory containing `.git` is owned by a different UID than the EUID of `git` >= 2.35.2 which became available in newer Ubuntu repos today, Tuesday. This immediately broke container-based builds unless the RUNAS UID of the runner container process happens to match the workspace owner on the runner VM.
> Error: fatal: unsafe repository ('/__w/ziti-tunnel-sdk-c/ziti-tunnel-sdk-c' is owned by someone else)
This also applies to Docker Actions that run directly on a runner VM or inside a runner container, and this PR addresses both where:
* `/__w/ziti-tunnel-sdk-c/ziti-tunnel-sdk-c` is the workspace directory that Git sees inside the runner container, and 
* `/github/workspace` is the workpace directory that Git sees inside the …

declare "safe" dirs to Git if owned by another UID

---

lib/ziti-tunnel/include/ziti/ziti_tunnel.h
lib/ziti-tunnel/ziti_tunnel.c
programs/ziti-edge-tunnel/ziti-edge-tunnel.c

adding --disable-intercepts or -h option to the run method that allows user to run the tunneller in host only mode

host only tunneler

---

lib/ziti-tunnel-cbs/include/ziti/ziti_dns.h
lib/ziti-tunnel-cbs/ziti_dns.c
programs/ziti-edge-tunnel/ziti-edge-tunnel.c

Replace the string argument to ziti_dns_setup. fwiw I originally changed it to ip_addr_t to avoid the int -> string -> int conversion that ziti-edge-tunnel was doing.

use string for ziti_dns_setup's dns_addr argument

---

CMakeLists.txt
lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c
programs/ziti-edge-tunnel/include/log-utils.h
programs/ziti-edge-tunnel/include/windows/windows-service.h
programs/ziti-edge-tunnel/log_utils.c
programs/ziti-edge-tunnel/windows-service.c
programs/ziti-edge-tunnel/ziti-edge-tunnel.c

closes #444 
* remove multiwriter bool and related stuff
* update format away from %FT%T as it is inconsistent on windows. replace with long form
* add function to grant SE_DEBUG to the executing process
* change the way dates print to not be reliant on log init

Allow ZDEW to enumerate all/more/most processes when eval'ing posture checks

---

README.md

Relates to https://github.com/openziti/ziti-doc/pull/138

move doc fragments about tunnelers to main article in ziti-docs

---

programs/ziti-edge-tunnel/instance.c

closes #454
`-i` doesn't read the config file. have to decide if we want that or not when using `-i`

if log_level is not set, return default INFO

---

lib/ziti-tunnel/ziti_tunnel.c
programs/ziti-edge-tunnel/instance-config.c
programs/ziti-edge-tunnel/ziti-edge-tunnel.c

closes #464 
change two warns to debug and stop using `ZITI_LOG_DEFAULT_LEVEL` since the c sdk changed behaviors recently. Use INFO explicitly until processing the actual setting so certain startup messages are not skipped

use info on startup until processing actual log level. fix a warn->debug

---

programs/ziti-edge-tunnel/instance.c
programs/ziti-edge-tunnel/ziti-edge-tunnel.c

closes #466 
closes #465
* use tun ip for the 'IP' field
* when calculating IP of tun - use the ip provided
* add to the tunip to get the dns ip

fixes tun ip being incorrectly reported to zdew

---

docker/docker-compose.yml
docker/docker-entrypoint.sh

Also, start using Ziti env var names mapped to existing NF names e.g. `ZITI_ENROLL_TOKEN` instead of `NF_REG_TOKEN` while preserving backwards compat.

Docker get Ziti ID from env var instead of mounted file

---

.github/workflows/cmake.yml
.github/workflows/release.yml

Use containers when building linux artifacts. this lets us use any version of any distro that we want for builds, without needing to "upgrade" when GitHub deprecates linux runners.
For now the runner is pinned at ubuntu-20.04 to ensure the oldest possible kernel. I left the build os at ubuntu-18.04, so that the builds are effectively unchanged from what we were getting before this PR. Of course we can now easily go back to an older distro if we want.
The release workflow also re-uses the cmake workflow instead of copying/pasting it. I'm sure we can use similar tricks to fold some of the cpack workflow, but this seems like a worthwhile improvement for now.

build linux artifacts in containers. re-use cmake workflow.

---

CMakeLists.txt

0.30.2 fixes build errors with mingw, which is used by zdew

update ziti-sdk-c to 0.30.2

---

programs/ziti-edge-tunnel/ziti-edge-tunnel.c

`getopt_long` takes an array of `struct option` to represent recognized command line options. `struct option` has a field `has_arg` which specifies whether or not the command line option has an associated argument; possible values are:
- `no_argument`:            no argument to the option is expected
- `required_argument`:      an argument to the option is required
- `optional_argument`:      an argument to the option may be presented
We've been incorrectly setting this field to `optional_argument` in some cases when the intent was to make the command line option itself optional. This PR sets `has_arg` to `required_argument` where appropriate, and adds logic to ensure that required options are passed.

Use correct has_arg when parsing command line options with getopt_long

---

programs/ziti-edge-tunnel/ziti-edge-tunnel.c

fixes #268
fixes #532
fixes #516

Don't overwrite identity json when enrolling

---

CMakeLists.txt
lib/ziti-tunnel/CMakeLists.txt
lib/ziti-tunnel/intercept.c
lib/ziti-tunnel/lwip/lwipopts.h

The `BYTE_ORDER` C preprocessor macro is needed by lwip, but the lwip includes (and -contrib packages) don't always include the correct system includes to pick up a definition of `BYTE_ORDER`. It turns out that there is no standard include file for getting `BYTE_ORDER`, so this PR relies on a `cmake` variable, but only if `BYTE_ORDER` is not already defined.

Ensure that BYTE_ORDER is set

---

.github/actions/openziti-tunnel-build-action/ubuntu-20.04/Dockerfile

The cmake scripts now reference `CMAKE_C_BYTE_ORDER`, which is defined by cmake 3.20 and later.

get cmake 3.22 when building on ubuntu 20

---

programs/ziti-edge-tunnel/ziti-edge-tunnel.c

Resolves #488 issue. The checks for opts were wrong in 5 functions: verify/remove/submit_mfa & generate/get_mfa_codes. All of them expected long version of the opt to be '--code', instead of '--authcode' as the docs say.

Fix --authcode option parsing.

---

programs/ziti-edge-tunnel/windows/log_utils.c

Resolves #486. Check also a month and year difference (will prevent a bug where log would not be rotated at the end of the year).

Fix bug where log doesn't rotate at the end of a month.

---

CMakeLists.txt

ziti-sdk-c 0.30.8 fixes https://github.com/openziti/ziti-sdk-c/issues/475, which caused tunnelers to hang when intercept.v1 or host.v1 service configurations were updated

get ziti-sdk-c 0.30.8

---

.github/workflows/cpack.yml

Now that we serve multiple architectures, we need to partition the upload keyspace by architecture. The architecture is also stored in the metadata of the Debian package. Still, the uploads for 0.20.10 were clobbered because all architectures uploaded to the same path, and the package build artifacts have identical filenames.

upload deb to arch subkey

---

lib/ziti-tunnel-cbs/ziti_tunnel_cbs.c

fix wildcard matches

---

lib/ziti-tunnel-cbs/ziti_dns.c

don't reject queried or loaded hostnames based on "acceptable" characters

---

programs/ziti-edge-tunnel/netif_driver/darwin/utun.c

This change allows multiple ziti-edge-tunnel instances on Darwin - as long as you give each one a unique DNS range. I know we don't officially support multiple instances, but I've been relying on it for my dev environment and it comes in handy.

use full mask when setting address on utun device

---

programs/ziti-edge-tunnel/netif_driver/linux/tun.c

Every exclude_rt was derived from the system's default route (``ip route show default``). This causes the communication to the controllers and edge routers to use the default gateway even if the system had a more preferred route for those destinations. In the worst case, the destination is unreachable from the default route, causing loss of communications.
This fix addresses this behavior by looking up the system's preferred route for the destination and then deriving the exclude_rt from that route.
A secondary benefit of this approach is that the ``ziti-edge-tunnel`` can use indirect underlays such as ``Speedify`` or ``Tailscale`` to communicate with the controllers and edge routers. One of the benefits of indirect underlays is increasing the likelihood communications passing firewalls …

Fix: Derive the exclude_rt from the preferred route

---

programs/ziti-edge-tunnel/netif_driver/linux/tun.c

Allocate a tun network device with name ``ziti0``. 
When allocating a device, ``ifr.ifr_name`` accepts a format string with the ``%d`` specifier. The OS then will allocate a device with the generated name. The field ``ifr.ifr_name`` is overwritten with name and returned to the user.

Allocate tun network device with name "ziti0"

---

programs/ziti-edge-tunnel/ziti-edge-tunnel.c

improve help for on/off identity command

---

lib/ziti-tunnel-cbs/include/ziti/ziti_tunnel_cbs.h
lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c
programs/ziti-edge-tunnel/ziti-edge-tunnel.c

fix `run --refresh ` parameter

---

programs/ziti-edge-tunnel/netif_driver/linux/tun.c

Newer versions of `grep` eagerly write:
`fgrep: warning: fgrep is obsolescent; using grep -F`
This PR aligns with the recomendation to use `grep -F` instead of `fgrep`.

Remove obsolete fgrep

---

programs/ziti-edge-tunnel/ziti-edge-tunnel.c

fix: enroll with pkcs11 key

---

.github/workflows/cmake.yml
.github/workflows/cpack.yml

also sneaking in a hopeful fix for invalid version strings in linux builds.

push packages to artifactory again

---

.github/workflows/cpack.yml

The `!github.event.release.prerelease` test is still needed, but not sufficient since it evaluates to true for non-release events. check the event type first.

only upload packages to artifactory for release events

---

lib/ziti-tunnel-cbs/include/ziti/ziti_tunnel_cbs.h
lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c

- re-write config file or external CA bundle file

process CA bundle event

---

programs/ziti-edge-tunnel/ziti-edge-tunnel.c

output error for user
[fixes #733]

avoid crash if -l or --loglevel option is not specified.

---

.github/workflows/linters.yml
BUILD.md
README.md
programs/ziti-edge-tunnel/package/deb/postrm.in
scripts/openwrt-build.sh

Hi,
this is a trivial PR, adding the [codespell](https://github.com/codespell-project/actions-codespell) tool to the CI, and fixing some non-code misspelling cases.
The CI file is called `linters.yml`, so that this can be extended in a future with other linter tools.
Best regards,
Mario

codespell: Add spelling check and fix all issues

---

lib/ziti-tunnel/tunnel_tcp.c
lib/ziti-tunnel/tunnel_udp.c

`LOG_STATE` now looks like this:
```
VERBOSE tunnel-sdk:tunnel_tcp.c:141 on_tcp_client_data() status 0 src[tcp:100.64.1.1:64905] dst[tcp:100.64.1.5:22] state[4/ESTABLISHED] flags[0x101] service[ssh]
```
incoming segments now look like this:
```
TRACE tunnel-sdk:tunnel_tcp.c:366 recv_tcp() received segment src[tcp:100.64.1.1:64905] dst[tcp:100.64.1.5:22] flags[PSH,ACK]
```

log tcp src and dst in LOG_STATE. also log tcp flags of incoming segments

---

programs/ziti-edge-tunnel/package/deb/postinst.in
programs/ziti-edge-tunnel/package/rpm/post.sh.in

...when installing the package non-interactively

stop emitting an error about stdin not being a tty

---

programs/ziti-edge-tunnel/package/deb/postinst.in
programs/ziti-edge-tunnel/package/rpm/post.sh.in

Fixes these install errors on Debian caused by failing to check if the file exists before unblinking, and failing to quote a variable that might be undefined.
```
Setting up ziti-edge-tunnel (0.22.22) ...
unlink: cannot unlink '/opt/openziti/share/ziti-edge-tunnel.service': No such file or directory
/var/lib/dpkg/info/ziti-edge-tunnel.postinst: 109: [: !=: unexpected operator
```

correct the deb and rpm hooks

---

.github/dependabot.yml

Hi,
This just configured dependabot for github-actions, analog to https://github.com/openziti/ziti/pull/1747
Thank you!

ci: Add dependabot for github-actions

---

docker/Dockerfile.base

This enables health checks to parse the output of the `tunnel_status` command correctly, e.g., [this liveness probe idea](https://github.com/openziti/helm-charts/pull/171#discussion_r1499466420).

install jq in container image

---

lib/ziti-tunnel-cbs/ziti_dns.c

Using a map iterator after removing the last item from the map can lead to invalid reads.
```
==1994639== Invalid read of size 8
==1994639==    at 0x159779: model_map_it_next (model_collections.c:245)
==1994639==    by 0x16FB6C: ziti_dns_deregister_intercept (ziti_dns.c:378)
==1994639==    by 0x163231: stop_intercept (ziti_tunnel_cbs.c:503)
==1994639==    by 0x163231: ziti_sdk_c_on_service (ziti_tunnel_cbs.c:571)
==1994639==    by 0x167948: on_service (ziti_tunnel_ctrl.c:725)
==1994639==    by 0x167DF7: on_ziti_event (ziti_tunnel_ctrl.c:800)
```

advance map iterators with model_map_it_remove when removing map items

---

programs/ziti-edge-tunnel/netif_driver/linux/resolvers.c
programs/ziti-edge-tunnel/netif_driver/linux/resolvers.h
programs/ziti-edge-tunnel/netif_driver/linux/tun.c

this PR fixes an issue that was observed in the smoke tests where IP of ZET's DNS server was. not configured into the host's resolver. all of the systemd API calls that we make to set up the resolver with the IP of our DNS server were successful. I added debug logs to check the resolver settings (with `resolvectl dns ziti0`)  immediately after they were made and the settings were as expected, but once in a while shortly after this check, the DNS server list was cleared.

wait for systemd tun device unit to be active before configuring dns

---

CMakeLists.txt
programs/ziti-edge-tunnel/ziti-edge-tunnel.c

This matches the behavior of [golang's proxy url processing](https://cs.opensource.google/go/x/net/+/master:http/httpproxy/proxy.go;drc=66e838c6fbf5387ecedc26ce490b5f4d6864a854;l=146), and enables HTTP_PROXY to be set with the same format that the ER recognizes.

Assume http proxy if type is not specified

---

programs/ziti-edge-tunnel/instance.c
programs/ziti-edge-tunnel/ziti-edge-tunnel.c

also don't let log level from config file replace the cmdline value.

initialize ziti logger before command line parsing

---

CMakeLists.txt

includes fixes to prevent new requests when controller is unavailable

get ziti-sdk-c 1.0.4

---

programs/ziti-edge-tunnel/ziti-edge-tunnel.c

avoids unwanted logger initialization messages for subcommands like `version`.

initialize logger after command line parsing; use fprintf before then

---

.github/workflows/cmake.yml

macOS-11 currently has scheduled brownouts and will be deprecated soon

Update macOS runner

---

CMakeLists.txt

includes fix for empty endpoint map.

get ziti-sdk-c v2.0.0-alpha8

---

lib/ziti-tunnel-cbs/include/ziti/ziti_tunnel_cbs.h
lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c

this adds more flexibility to applications using tunnelers SDK (primarily mobile tunnelers)

allow loading/starting ziti identity with provided config instead of file

---

.gitignore
lib/ziti-tunnel-cbs/include/ziti/ziti_tunnel_cbs.h
lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c
programs/ziti-edge-tunnel/include/model/dtos.h
programs/ziti-edge-tunnel/instance.c
programs/ziti-edge-tunnel/ziti-edge-tunnel.c

closes #630 
remember the state of the tunneler whether identities are enabled or disabled.
clean up fields that don't seem to be used (famous last words)

remember enabled/disabled state

---

programs/ziti-edge-tunnel/ziti-edge-tunnel.c

ensure individual (not from config dir) tunnel identities are present in tunnel identities map

fix for identities not loading

---

lib/ziti-tunnel-cbs/ziti_dns.c
lib/ziti-tunnel-cbs/ziti_hosting.c
lib/ziti-tunnel-cbs/ziti_tunnel_cbs.c
programs/ziti-edge-tunnel/ziti-edge-tunnel.c

- always try to bind upstream socket to IPv6
- map IPv4 upstream address to IPv6
mobile clients may change upstream DNS as they switch networks

support both IPv4/6 DNS upstreams

---

.github/actions/build/action.yml
.github/workflows/cmake.yml
.github/workflows/release.yml
CMakePresets.json

feat: add static builds presets (1.x)

---

.github/workflows/publish-container-images.yml

I meant to include this commit in https://github.com/openziti/ziti-tunnel-sdk-c/pull/964

fix artifact filenames for container images

---

programs/ziti-edge-tunnel/ziti-edge-tunnel.c

looks like ZDEW is adding NRPT rules when there's no dial permission:
https://openziti.discourse.group/t/wde-breaks-windows-dns-on-dc/3140/6

only add nrpt entry when the service has dial permission

---

lib/ziti-tunnel-cbs/ziti_tunnel_cbs.c
lib/ziti-tunnel/tunnel_tcp.c

This avoids double closing tcp handles, which leads to circular tcp connection list.

Handle failed tcp conns before ziti dial

---

lib/ziti-tunnel-cbs/ziti_tunnel_cbs.c
lib/ziti-tunnel/tunnel_tcp.c

cherry picked from release-1.x.
fixes #961

set tcp error callback sooner so tcp errors that happen while waiting for ziti_dial can be handled

---

.github/actions/build/action.yml
.github/actions/openziti-tunnel-build-action/gh-release/entrypoint.sh
.github/actions/openziti-tunnel-build-action/redhat-8/entrypoint.sh
.github/actions/openziti-tunnel-build-action/redhat-9/entrypoint.sh
.github/actions/openziti-tunnel-build-action/ubuntu-20.04/entrypoint.sh
.github/actions/openziti-tunnel-build-action/ubuntu-22.04/entrypoint.sh
.github/workflows/cmake.yml
.github/workflows/cpack.yml

This PR updates the workflows to completely control vcpkg caching.
* disables the caching that was set up by `run-vcpkg`
* configures vcpkg's cache to be a directory within the GitHub workspace, so it can be accessed from build steps and containers.
* caches are used for cpack builds as well as gh releases. each intentionally has a different key.

CI caching improvements

---

programs/ziti-edge-tunnel/instance.c
programs/ziti-edge-tunnel/ziti-edge-tunnel.c

merged from and supersedes #1000

Rc add zfw calls main

---

.github/actions/build/action.yml
.github/actions/openziti-tunnel-build-action/redhat-8/Dockerfile
.github/workflows/cpack.yml

include image version in vcpkg cache keys, otherwise `actions/cache` finds a hit but vcpkg needs to rebuild everything.

improve vcpkg cache hits

---

CMakeLists.txt
programs/ziti-edge-tunnel/ziti-edge-tunnel.c

[fixes #1038]
update ziti-sdk@1.2.1
```
$ ziti-edge-tunnel refresh -h
ziti-edge-tunnel refresh: refresh identity
usage: ziti-edge-tunnel refresh [-i <identity>]
-i|--identity   identity to be refreshed
$ ziti-edge-tunnel refresh -i etc/mm.json                                                                             
{
"Success":true,
"Code":0
}
```

add CLI refresh command

---

deps/CMakeLists.txt
lib/ziti-tunnel/CMakeLists.txt
programs/CMakeLists.txt

also use FetchContent_MakeAvailable to avoid deprecation warnings

get lwip ports from lwip project instead of abandoned lwip-contrib project

---

lib/ziti-tunnel/include/ziti/netif_driver.h
programs/ziti-edge-tunnel/include/identity-utils.h
programs/ziti-edge-tunnel/include/windows/windows-scripts.h
programs/ziti-edge-tunnel/instance.c
programs/ziti-edge-tunnel/netif_driver/darwin/utun.c
programs/ziti-edge-tunnel/netif_driver/darwin/utun.h
programs/ziti-edge-tunnel/netif_driver/linux/tun.c
programs/ziti-edge-tunnel/netif_driver/linux/tun.h
programs/ziti-edge-tunnel/netif_driver/windows/tun.c
programs/ziti-edge-tunnel/netif_driver/windows/tun.h
programs/ziti-edge-tunnel/process_cmd.c
programs/ziti-edge-tunnel/windows-scripts.c
programs/ziti-edge-tunnel/ziti-edge-tunnel.c

add get_name to the driver per request from the previous PR

Add get_name to netif driver

---

lib/ziti-tunnel-cbs/include/ziti/ziti_tunnel_cbs.h
lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c
programs/ziti-edge-tunnel/config-utils.c
programs/ziti-edge-tunnel/include/config-utils.h
programs/ziti-edge-tunnel/ziti-edge-tunnel.c

tunneler SDK should not make assumptions on how config is stored

move config file update from tunneler lib to ZET

---

toolchains/Linux-arm.cmake

This is preparatory. We're not presently shipping ARM(64) RPMs with CPack for ziti-edge-tunnel.

correct the target architecture string for arm RPM

---

programs/ziti-edge-tunnel/ziti-edge-tunnel.c

fixes a problem when after a failed external auth via timeout, the client would get an erroneous "NeedsExtAuth = false"

No event on timeout

---

programs/ziti-edge-tunnel/CMakeLists.txt
programs/ziti-edge-tunnel/windows/log_utils.c
programs/ziti-edge-tunnel/windows/minidump.c
programs/ziti-edge-tunnel/windows/minidump.h
programs/ziti-edge-tunnel/ziti-edge-tunnel.c

writes a mini crash dump with thread info file on unhandled exceptions

write a minidump if ziti-edge-tunnel crashes on windows

---

.github/workflows/cpack.yml
.github/workflows/promote-downstreams.yml

avoids unintentionally promoting alpha|beta like this https://github.com/openziti/ziti-tunnel-sdk-c/actions/runs/12433449820/job/34717192902

only promote stable package version '1', not alpha|beta packages

---

CMakeLists.txt

if ZITI_DEBUG is declared, define a symbol to trigger debuggier logging in the c sdk
depends on https://github.com/openziti/ziti-sdk-c/pull/811/files

allow ZITI_DEBUG to be defined

---

lib/ziti-tunnel-cbs/ziti_hosting.c

also use defaults for int values that are set (to 0) in the config struct even when not set in json

set max connection timeout value in listen options

---

CMakePresets.json
vcpkg-overlays/omit-json-c-apps/README.md
vcpkg-overlays/omit-json-c-apps/json-c/fix-clang-cl.patch
vcpkg-overlays/omit-json-c-apps/json-c/pkgconfig.patch
vcpkg-overlays/omit-json-c-apps/json-c/portfile.cmake
vcpkg-overlays/omit-json-c-apps/json-c/vcpkg.json

Disable the portion of the build that currently breaks when building with cmake 4 (json-c apps). This is preferable to controlling the cmake version used by vcpkg, as was done in https://github.com/openziti/ziti-tunnel-sdk-c/pull/1130/commits/3cac744697e720a1525a859a23bf26f83ab6727c and https://github.com/openziti/ziti-tunnel-sdk-c/pull/1134.

allow building with cmake 4.0

---

.github/workflows/cmake.yml
CMakeLists.txt
lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c
programs/ziti-edge-tunnel/ipc_cmd.c

- process multiple commands from the same IPC connection;
- make sure `TunnelCommand_Enroll` errors are getting appropriate responses.

IPC: improvements

---

programs/ziti-edge-tunnel/ziti-edge-tunnel.c

leak was added in #1089 (release [1.4.5](https://github.com/openziti/ziti-tunnel-sdk-c/releases/tag/v1.4.5))

free ziti_config memory after sending identity event

---

programs/ziti-edge-tunnel/package/deb/postinst.in
programs/ziti-edge-tunnel/package/rpm/post.sh.in

This is necessary for:
1. write state to config.json
2. for edge SDK to update client certs, private key, trust bundle

allow posix ziti:ziti to rewrite *.json files in identity dir

---

CMakeLists.txt
programs/ziti-edge-tunnel/CMakeLists.txt

target `ziti-edge-tunnel` may not exist

move setting ziti-edge-tunnel compile definitions (execinfo)

---

.github/actions/openziti-tunnel-build-action/action.yml
.github/actions/openziti-tunnel-build-action/gh-release/Dockerfile
.github/actions/openziti-tunnel-build-action/gh-release/entrypoint.sh
.github/actions/openziti-tunnel-build-action/redhat-8/Dockerfile
.github/actions/openziti-tunnel-build-action/redhat-8/entrypoint.sh
.github/actions/openziti-tunnel-build-action/redhat-9/Dockerfile
.github/actions/openziti-tunnel-build-action/redhat-9/entrypoint.sh
.github/actions/openziti-tunnel-build-action/ubuntu-20.04/Dockerfile
.github/actions/openziti-tunnel-build-action/ubuntu-20.04/entrypoint.sh
.github/actions/openziti-tunnel-build-action/ubuntu-22.04/Dockerfile
.github/actions/openziti-tunnel-build-action/ubuntu-22.04/entrypoint.sh
.github/workflows/cpack.yml
.github/workflows/promote-downstreams.yml
.gitignore

the redhat9 builder encountered an issue, possibly surfaced by yesterday's github platform widespread outage, so I audited the workflow and [added a redhat10 distribution](https://github.com/openziti/ziti-tunnel-sdk-c/pull/1184).
```
36.54 Error:                                                                                                                                                                                                                                             
36.54  Problem 1: cannot install the best candidate for the job                                                                                                                                                                                          
36.54   - nothing provides glibc = 2.34-168.el9_6.19 needed by …
```

bugfix and tidy cpack action and workflow
