openziti/ziti-tunnel-sdk-c

lib/ziti_tunneler.c, lib/ziti_tunneler_cbs.c
=> avoid ERR_MEM -- let C-sdk buffer data

lib/tunneler_tcp.c, lib/tunneler_udp.c
The edge router is smart enough to kill connections for services that become unavailable to an identity, so there isn't anything significant to do here.
=> Connection sniping

include/ziti/ziti_tunneler.h, lib/CMakeLists.txt, lib/dns.c, lib/ziti_tunneler.c, lib/ziti_tunneler_priv.h, programs/ziti-tunnel-app/CMakeLists.txt, programs/ziti-tunnel-app/dnsmasq_manager.c, programs/ziti-tunnel-app/netif_driver/linux/tun.c, programs/ziti-tunnel-app/netif_driver/linux/tun.h, programs/ziti-tunnel-app/ziti-tunnel-app.c
adds DNS assignment into tunneler core
adds support for dnsmasq DNS resolution
=> Dns support dnsmasq

.github/workflows/cmake.yml
=> Windows CI

CMakeLists.txt, deps/CMakeLists.txt
=> Openwrt package

deps/CMakeLists.txt, include/ziti/ziti_tunnel.h, include/ziti/ziti_tunnel_cbs.h, lib/tunnel_tcp.c, lib/tunnel_tcp.h, lib/ziti_tunnel.c, lib/ziti_tunnel_cbs.c
implements TCP half-close support:
* intercepted connections - DONE
* hosted connections - TODO
=> implement half-close

.github/workflows/bump.yml, deps/CMakeLists.txt, lib/tunnel_tcp.c, lib/ziti_tunnel_cbs.c
=> terminate ziti connection on client errors

.github/workflows/cmake.yml
noticed the windows build was crazy fast - it wasn't actually building
=> update github workflow

CMakeLists.txt, deps/CMakeLists.txt
quick pr to make it easy for someone using the tunneler sdk to change out the csdk used
=> Allow easy csdk override

CMakeLists.txt, docs/openwrt/ziti.init
=> openwrt: restart service on wan network change

CMakeLists.txt, lib/ziti_tunnel.c, lib/ziti_tunnel_cbs.c, programs/ziti-edge-tunnel/ziti-edge-tunnel.c
fix memory leaks on hosted connections
=> update ziti-sdk-c to v0.18.2

CMakeLists.txt
bring in latest csdk which prevents data_cb from happening on closed connection
=> update ziti sdk

CMakeLists.txt
https://cmake.org/cmake/help/v3.14/release/3.14.html
=> ensure that FetchContent_MakeAvaialble is available

.github/workflows/bump.yml, .github/workflows/cmake.yml, toolchains/default.cmake
use ubuntu-16.04
consolidate jobs
add linux ARM build
update release workflow
=> add build for linux on ARM

CMakeLists.txt
- fixes file descriptor leaks under certain circumstances
- implelements services-update check to avoid frequent full reloads
=> pull ziti-sdk-c v0.20.3

include/ziti/ziti_tunnel.h, lib/tunnel_tcp.c, lib/tunnel_udp.c, lib/ziti_tunnel.c, lib/ziti_tunnel_cbs.c
I'm still testing but I wanted to get some eyes on this any maybe some additional tire kicking.
=> close intercept sessions in controlled sequence

CMakeLists.txt
fixes rebinding of hosted connections
=> pull ziti-sdk-c 0.20.12

programs/ziti-edge-tunnel/netif_driver/linux/tun.c, programs/ziti-edge-tunnel/netif_driver/linux/tun.h, programs/ziti-edge-tunnel/ziti-edge-tunnel.c
this change addresses the issue of DNS server removed from tun interface on any network change event
=> maintain DNS server assignment on tun interface

CMakeLists.txt
=> pull latest ziti-sdk-c release

programs/ziti-edge-tunnel/netif_driver/linux/tun.c
This PR attempts to set the tun's domain routing to match the other resolvers in the system.
It isn't perfect - it doesn't filter resolvers that have domain routing set but no DNS servers, but works without manual intervention on mostly stock Ubuntu 20 and Fedora 33.
=> set wildcard domain on tun resolver only if other resolvers use the wildcard domain

programs/ziti-edge-tunnel/netif_driver/linux/tun.c
- use WEXITSTATUS to examine exit status
- nonzero exit status is not necessarily an error
- clean up va_list variables
=> cleanup logging when running resolvectl domain test 

README.md, programs/ziti-edge-tunnel/ziti-edge-tunnel.c
update README.md with running on Linux instructions
=> change options for consistency [#minor]

CMakeLists.txt
=> bump ziti-sdk-c

lib/ziti-tunnel-cbs/CMakeLists.txt, lib/ziti-tunnel-cbs/include/ziti/ziti_tunnel_cbs.h, lib/ziti-tunnel-cbs/ziti_instance.h, lib/ziti-tunnel-cbs/ziti_tunnel_cbs.c, lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c, lib/ziti-tunnel/include/ziti/ziti_tunnel.h, lib/ziti-tunnel/tunnel_tcp.c, lib/ziti-tunnel/tunnel_tcp.h, lib/ziti-tunnel/tunnel_udp.c, lib/ziti-tunnel/tunnel_udp.h, lib/ziti-tunnel/ziti_tunnel.c, lib/ziti-tunnel/ziti_tunnel_priv.h
this makes intercept API more abstracted
=> tunnel SDK API refactor - I

CMakeLists.txt, lib/ziti-tunnel-cbs/ziti_hosting.c, lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c, programs/ziti-edge-tunnel/CMakeLists.txt, programs/ziti-edge-tunnel/dnsmasq_manager.c, programs/ziti-edge-tunnel/netif_driver/windows/tun.c, programs/ziti-edge-tunnel/ziti-edge-tunnel.c
=> fixes for MSVC build

lib/ziti-tunnel-cbs/include/ziti/ziti_tunnel_cbs.h, lib/ziti-tunnel-cbs/ziti_instance.h, lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c, programs/ziti-edge-tunnel/ziti-edge-tunnel.c
implement MFA auth support (event/command)
=> define API for propagating Tunnel Ziti events

CMakeLists.txt, lib/ziti-tunnel-cbs/ziti_instance.h, lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c, lib/ziti-tunnel/lwip/lwipopts.h, lib/ziti-tunnel/ziti_tunnel.c, lib/ziti-tunnel/ziti_tunnel_priv.h
MFA callback are gone, will be put back in #169
=> Update ziti sdk c

CMakeLists.txt, lib/ziti-tunnel-cbs/ziti_hosting.c, lib/ziti-tunnel/tunnel_tcp.c, lib/ziti-tunnel/tunnel_udp.c, lib/ziti-tunnel/ziti_tunnel.c, lib/ziti-tunnel/ziti_tunnel_priv.h
=> UDP timeout

lib/ziti-tunnel-cbs/ziti_tunnel_cbs.c, lib/ziti-tunnel/include/ziti/ziti_tunnel.h, lib/ziti-tunnel/intercept.c, lib/ziti-tunnel/ziti_tunnel.c, lib/ziti-tunnel/ziti_tunnel_priv.h
check if intercept configuration changed and act accordingly
also, fix memory leaks of intercept configurations
=> process service change events (intercepts only)

lib/ziti-tunnel-cbs/ziti_tunnel_cbs.c
fixes crash for hosted-only services
=> handle no current intercept

lib/ziti-tunnel-cbs/include/ziti/ziti_tunnel_cbs.h, lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c, programs/CMakeLists.txt, programs/tests/CMakeLists.txt, programs/tests/ziti-edge-tunnel-test.c, programs/ziti-edge-tunnel/CMakeLists.txt, programs/ziti-edge-tunnel/events/events.h, programs/ziti-edge-tunnel/include/instance.h, programs/ziti-edge-tunnel/include/model/dtos.h, programs/ziti-edge-tunnel/include/model/events.h, programs/ziti-edge-tunnel/instance.c, programs/ziti-edge-tunnel/ziti-edge-tunnel.c
Sending identity message with minimum information to the client pipe. I will continue working on the event messages. This is initial PR for the broadcast events message.
=> Broadcast message pipe

lib/ziti-tunnel-cbs/include/ziti/ziti_tunnel_cbs.h, lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c, programs/tests/ziti-edge-tunnel-test.c, programs/ziti-edge-tunnel/include/model/dtos.h, programs/ziti-edge-tunnel/instance.c, programs/ziti-edge-tunnel/ziti-edge-tunnel.c
fixed memory issues reported by valgrind
=> Fix memory issues

lib/ziti-tunnel-cbs/ziti_dns.c
=> send no response to AAAA queries

programs/ziti-edge-tunnel/ziti-edge-tunnel.c
Fix for the segmentation issue that Ken reported
=> fingerprint is not available in linux, adding null check

CMakeLists.txt
* API request page size opt
* API request logging improvements
=> update ziti-sdk-c v0.26.18

programs/ziti-edge-tunnel/netif_driver/linux/tun.c
cherry picking the route exclusion fix into 0.17.
=> v0.17: check default route for both via and dev specifications (#266)

CMakeLists.txt, lib/ziti-tunnel-cbs/CMakeLists.txt, lib/ziti-tunnel/include/ziti/ziti_tunnel.h, lib/ziti-tunnel/ziti_tunnel_priv.h, programs/ziti-edge-tunnel/CMakeLists.txt
update to latest c sdk - which required changes to the logging function
=> Jan31 update sdk

lib/ziti-tunnel-cbs/include/ziti/ziti_tunnel_cbs.h, lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c, programs/ziti-edge-tunnel/include/model/dtos.h, programs/ziti-edge-tunnel/instance-config.c, programs/ziti-edge-tunnel/instance.c, programs/ziti-edge-tunnel/windows-scripts.c, programs/ziti-edge-tunnel/ziti-edge-tunnel.c
Adding Code field as UI depends on this status code. Changed Status field to IdFileStatus, as old config file already has a Status field which is of string data type
=> Tunnel status code

lib/ziti-tunnel-cbs/include/ziti/ziti_tunnel_cbs.h, lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c, programs/ziti-edge-tunnel/ziti-edge-tunnel.c
send identity updated event when the url of the controller changes
=> New api event

programs/ziti-edge-tunnel/include/windows/windows-service.h, programs/ziti-edge-tunnel/windows-service.c, programs/ziti-edge-tunnel/ziti-edge-tunnel.c
https://github.com/openziti/desktop-edge-win/issues/514
fixing just the appname for now
=> fix the appname reported by app

programs/ziti-edge-tunnel/include/windows/windows-service.h, programs/ziti-edge-tunnel/windows-scripts.c, programs/ziti-edge-tunnel/windows-service.c
Changing service name in services.msc from ziti-edge-tunnel to ziti
=> Ziti service name

lib/ziti-tunnel-cbs/include/ziti/ziti_tunnel_cbs.h, lib/ziti-tunnel-cbs/ziti_instance.h, lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c
in support of Apple Desktop and Mobile Edge apps...
=> Support externally loaded ziti identities

lib/ziti-tunnel-cbs/ziti_dns.c
fix leak: drop duplicate requests
=> fix crash: really remove deleted request from the map

lib/ziti-tunnel-cbs/ziti_hosting.c
Fixes crash when host.v1 config specifies `listen_options`
=> ziti_host_cfg_v1.listen_options is a real struct

.github/actions/openziti-tunnel-build-action/ubuntu-16.04/Dockerfile, .github/actions/openziti-tunnel-build-action/ubuntu-16.04/entrypoint.sh, programs/ziti-edge-tunnel/netif_driver/linux/resolvers.c, programs/ziti-edge-tunnel/netif_driver/linux/resolvers.h, programs/ziti-edge-tunnel/netif_driver/linux/tun.c, programs/ziti-edge-tunnel/netif_driver/linux/utils.c, programs/ziti-edge-tunnel/netif_driver/linux/utils.h, programs/ziti-edge-tunnel/package/systemd/ziti-edge-tunnel.sh.in, programs/ziti-edge-tunnel/ziti-edge-tunnel.c, scripts/openwrt-build.sh
@sabedevops 's systemd fixes and a script fix to delete the OTT JWT file after successfully enrolling
=> systemd fixes

lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c, lib/ziti-tunnel/include/ziti/netif_driver.h, lib/ziti-tunnel/include/ziti/ziti_tunnel.h, lib/ziti-tunnel/ziti_tunnel.c, programs/ziti-edge-tunnel/netif_driver/linux/tun.c, programs/ziti-edge-tunnel/netif_driver/linux/tun.h
API to allow netif drivers to implement route updates batching
implement route batching for Linux
[fixes #418]
=> Implement route update batching

docker/Dockerfile, docker/docker-entrypoint.sh
to allow for stuffing identity in local images that are never published
=> stop requiring docker mount 

.github/workflows/mattermost-ziti-webhook.yml
Update to use the python-based action
=> Update to ziti-mattermost-action-py

lib/ziti-tunnel/tunnel_udp.c
=> free queued pbuf when closing udp connections

lib/ziti-tunnel/tests/address_test.cpp, tests/CMakeLists.txt
link all_tests runner with tsdk tests library
=> add ziti-tunnel-sdk-c tests to all runner.

programs/ziti-edge-tunnel/instance.c, programs/ziti-edge-tunnel/windows-scripts.c, programs/ziti-edge-tunnel/ziti-edge-tunnel.c
=> don't set mfa needed on startup when reading config file

CMakeLists.txt, lib/tests/CMakeLists.txt, lib/tests/dns_test.cpp, lib/tests/tunnel_integ_test.cpp, lib/ziti-tunnel-cbs/include/ziti/ziti_dns.h, lib/ziti-tunnel-cbs/ziti_dns.c, lib/ziti-tunnel-cbs/ziti_tunnel_cbs.c, lib/ziti-tunnel/include/ziti/ziti_tunnel.h, lib/ziti-tunnel/intercept.c, programs/ziti-edge-tunnel/include/identity-utils.h, tests/CMakeLists.txt
closes https://github.com/openziti/ziti-tunnel-sdk-c/issues/475
=> recycle DNS ips

lib/ziti-tunnel-cbs/ziti_hosting.c
a few small things that helped when I was debugging voip services.
=> logging tweaks

programs/ziti-edge-tunnel/package/deb/postrm.in
=> Fix deb package removal script.

CMakeLists.txt, lib/ziti-tunnel/tunnel_tcp.c
=> Send RST to client when closing un-established connections

lib/ziti-tunnel-cbs/ziti_dns.c
=> always close underlay connection for dns queries

lib/ziti-tunnel/intercept.c
=> skip addresses that don't match

docker/README.md
* change the description of container image origination to reflect that they're auto-published with ZET releases
* grammar and punctuation for container README
=> update characterization of container images 

programs/ziti-edge-tunnel/netif_driver/linux/tun.c, programs/ziti-edge-tunnel/netif_driver/windows/tun.c, programs/ziti-edge-tunnel/netif_driver/windows/tun.h, programs/ziti-edge-tunnel/ziti-edge-tunnel.c
=> flush dns cache on Windows when starting and stopping

docker/Dockerfile.base, docker/docker-entrypoint.sh
=> set user after privileged copy command

CMakeLists.txt, lib/ziti-tunnel-cbs/ziti_tunnel_cbs.c, lib/ziti-tunnel/lwip/lwipopts.h, lib/ziti-tunnel/tunnel_tcp.c, lib/ziti-tunnel/tunnel_udp.c
also ensure close functions are called
also fixed leak of app_data object when dial_opts.identity wasn't set
also get csdk update with pls leak fixes
=> free pbufs when ziti_write fails

.github/workflows/cmake.yml, .gitignore, CMakeLists.txt, CMakePresets.json, HACKING.md, lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c, lib/ziti-tunnel/CMakeLists.txt, programs/tests/CMakeLists.txt, toolchains/Windows-arm64.cmake, toolchains/macOS-arm64.cmake, vcpkg.json
- use vcpkg to manage deps
- use CMake presets to manage build configurations
- update ziti-sdk to v0.32.0
=> Vcpkg cmake presets

docker/docker-compose.yml
…for the hello container inside the Docker bridge
=> correct the TCP port hint 

CMakeLists.txt
Brings support for terminator redundancy
=> update ziti-sdk@0.33.2: multi-terminator bind

lib/ziti-tunnel-cbs/ziti_hosting.c
=> use logical or when testing dial_protocol_str

.github/cpack-matrix.yml, .github/workflows/cmake.yml, .github/workflows/cpack.yml, .github/workflows/draft-release.yml, .github/workflows/promote-downstreams.yml, .github/workflows/publish-containers.yml, .github/workflows/release.yml, RELEASING.md, docker/Dockerfile.ziti-host, scripts/ziti-builder.sh
=> Prereleases and promote downstreams

.github/actions/build/action.yml, lib/ziti-tunnel-cbs/include/ziti/ziti_tunnel_cbs.h, lib/ziti-tunnel-cbs/ziti_dns.c, lib/ziti-tunnel-cbs/ziti_hosting.c, lib/ziti-tunnel-cbs/ziti_tunnel_cbs.c, programs/ziti-edge-tunnel/ziti-edge-tunnel.c
=> Resolve hostnames in uv worker threads

lib/ziti-tunnel-cbs/ziti_hosting.c
=> avoid crash when client sends app data with source_ip set.

docker/BUILD.md, docker/Dockerfile.ziti-host, docker/docker-entrypoint.sh
1. deprecate legacy vars
2.  fix the no-start problem with getting identity from a var
3. fix the no such PID problem when handling SIGINT
=> refactor docker entrypoint

lib/ziti-tunnel-cbs/dns_host.h, lib/ziti-tunnel-cbs/dns_msg.c
=> send dns queries upstream

.github/actions/openziti-tunnel-build-action/ubuntu-22.04/Dockerfile, .github/actions/openziti-tunnel-build-action/ubuntu-22.04/entrypoint.sh, BUILD.md, scripts/ziti-builder.sh
=> document cross-compiling ZET and DEB

lib/ziti-tunnel-cbs/dns_host.c
this is an error with Xcode 15.3
=> declare data pointer as const

lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c, programs/ziti-edge-tunnel/instance.c, programs/ziti-edge-tunnel/ziti-edge-tunnel.c
cherry pick the comit to main that made random warning cleanups. fix enrollment for networks requiring mfa
=> cherry pick commit to release-1.x

.github/workflows/cmake.yml, lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c, programs/ziti-edge-tunnel/instance.c, programs/ziti-edge-tunnel/ziti-edge-tunnel.c
=> Release 1.x

lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c
dump command (without file output) should return data in result instead of log
=> improve dump command

CMakeLists.txt
fixes builds on alpine, openwrt, possibly others
=> Ziti sdk c 1.0.8

CMakeLists.txt
=> update ziti-sdk-c to 1.0.9

lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c, programs/ziti-edge-tunnel/instance.c, programs/ziti-edge-tunnel/ziti-edge-tunnel.c
=> use ziti_set_enabled which properly closes/stops an identity

CMakeLists.txt, lib/ziti-tunnel-cbs/dns_host.c, lib/ziti-tunnel-cbs/dns_host.h, lib/ziti-tunnel-cbs/dns_msg.c, lib/ziti-tunnel-cbs/include/ziti/ziti_tunnel_cbs.h, lib/ziti-tunnel-cbs/ziti_dns.c, lib/ziti-tunnel-cbs/ziti_hosting.c, lib/ziti-tunnel-cbs/ziti_hosting.h, lib/ziti-tunnel-cbs/ziti_tunnel_cbs.c, lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c, lib/ziti-tunnel/ziti_tunnel.c, lib/ziti-tunnel/ziti_tunnel_priv.h, programs/ziti-edge-tunnel/config-utils.c, programs/ziti-edge-tunnel/include/identity-utils.h, programs/ziti-edge-tunnel/include/model/dtos.h, programs/ziti-edge-tunnel/include/model/events.h, programs/ziti-edge-tunnel/instance.c, programs/ziti-edge-tunnel/ziti-edge-tunnel.c
=> update model to new types

lib/ziti-tunnel-cbs/ziti_dns.c
=> Clear dns reqs when dns client closes

lib/ziti-tunnel-cbs/include/ziti/ziti_tunnel_cbs.h, lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c, lib/ziti-tunnel/include/ziti/ziti_tunnel.h, lib/ziti-tunnel/tunnel_tcp.c, lib/ziti-tunnel/tunnel_tcp.h, lib/ziti-tunnel/tunnel_udp.c, lib/ziti-tunnel/tunnel_udp.h, lib/ziti-tunnel/ziti_tunnel.c, programs/ziti-edge-tunnel/ziti-edge-tunnel.c
=> add ip_dump IPC command

CMakeLists.txt, lib/ziti-tunnel-cbs/include/ziti/ziti_tunnel_cbs.h, programs/ziti-edge-tunnel/ziti-edge-tunnel.c
=> Keychain support

.github/workflows/cmake.yml
see actions/runner-images#10721
=> update macos CI runner to 13

lib/ziti-tunnel-cbs/include/ziti/ziti_tunnel_cbs.h, lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c, programs/ziti-edge-tunnel/instance.c, programs/ziti-edge-tunnel/process_cmd.c, programs/ziti-edge-tunnel/windows-service.c, programs/ziti-edge-tunnel/windows/log_utils.c, programs/ziti-edge-tunnel/ziti-edge-tunnel.c
rename jwtFilename to idenityFilename
rework -i help to be more clear
=> Add identity from url cert key identity filename

lib/ziti-tunnel-cbs/include/ziti/ziti_tunnel_cbs.h, lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c
make sure all auth events are handled
=> update auth events

lib/ziti-tunnel-cbs/include/ziti/ziti_tunnel_cbs.h, lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c, programs/ziti-edge-tunnel/include/model/dtos.h, programs/ziti-edge-tunnel/ziti-edge-tunnel.c
Also populate ztAPIs in emitted tunnel identity events
=> Rename tunnel api event --> config event

docker/ziti-host.Dockerfile
allows ZET to create the IPC socket
=> run-as group ziti

lib/ziti-tunnel-cbs/ziti_tunnel_ctrl.c, programs/ziti-edge-tunnel/process_cmd.c
=> callback immediately if/when the url is not valid

CMakeLists.txt, CMakePresets.json, programs/ziti-edge-tunnel/ziti-edge-tunnel.c
Avoid the inclusion of EXECINFO when it is not available.
=> EXECINFO checking

docker/README.md, docker/docker-entrypoint.sh, programs/ziti-edge-tunnel/package/systemd/ziti-edge-tunnel.sh.in
warn about and handle more scenarios on Linux and be more consistent when messaging about writable identities
=> warn about and handle more writable identity problems

lib/ziti-tunnel-cbs/ziti_hosting.c, lib/ziti-tunnel-cbs/ziti_hosting.h, lib/ziti-tunnel-cbs/ziti_tunnel_cbs.c, lib/ziti-tunnel/include/ziti/ziti_tunnel.h
=> support address translation
